/* * Copyright (c) 2026 Fordi / FomaDev. 
 * Licensed under FomaDev Public License.
 * See LICENSE file in the project root for full license information.
 */

import { RobotsOptions } from '../../types/robots.js';

/**
 * Extracts the origin (protocol + host) from an absolute URL.
 */
function extractRootDomain(url: string): string | null {
  try {
    const parsed = new URL(url);
    return parsed.origin;
  } catch {
    return null;
  }
}

/**
 * Normalizes a path to comply with the Robots.txt standard (must start with '/').
 */
function normalizePath(path: string): string {
  const trimmed = path.trim();
  if (!trimmed) return '';
  return trimmed.startsWith('/') ? trimmed : `/${trimmed}`;
}

/**
 * Cleans the generated content to guarantee RFC compliance:
 * - Removes trailing whitespace on each line
 * - Normalizes line breaks (LF)
 * - Collapses consecutive empty lines (max 1 empty line)
 */
function sanitizeRobotsOutput(content: string): string {
  return content
    .replace(/\r\n/g, '\n')              // LF normalization
    .split('\n')
    .map((line) => line.trimEnd())        // Removes trailing spaces
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')          // Max 1 consecutive empty line
    .trim();
}

/**
 * Generates the plain-text content for the robots.txt file.
 * v1.3.0: Native integration of the Robots.txt helper.
 * v1.3.1: Automatic root domain detection and chaining (Root Domain Auto-Discovery).
 * v1.3.2: Strict KnownUserAgent typing with IDE autocompletion.
 * v1.3.4: Automatic array mapping for exclusion directives (Disallow Array Mapping).
 * v1.3.5: Multi-sitemap support (Multi-Sitemap Array Injection).
 * v1.3.6: Full support for the Allow directive.
 * v1.3.7: Support for the non-standard Crawl-delay directive.
 * v1.3.8: Header metadata injection (# Generated by next-advanced-sitemap).
 * v1.3.9: Generator support for the text/plain HTTP response guard.
 * v1.3.10: Final RFC compliance validation (RFC Compliance Sanitizer & Guard).
 */
export function buildRobotsText(options: RobotsOptions): string {
  const buffer: string[] = [];

  // 🚀 v1.3.8: Metadata comment
  const generatedAt = new Date().toISOString();
  buffer.push(`# Generated by next-advanced-sitemap at ${generatedAt}\n\n`);

  const rules = Array.isArray(options.rules) ? options.rules : [options.rules];

  for (const rule of rules) {
    const userAgents = Array.isArray(rule.userAgent) ? rule.userAgent : [rule.userAgent];
    for (const agent of userAgents) {
      if (agent.trim()) {
        buffer.push(`User-agent: ${agent.trim()}\n`);
      }
    }

    if (rule.allow) {
      const allows = Array.isArray(rule.allow) ? rule.allow : [rule.allow];
      for (const path of allows) {
        if (path !== undefined && path !== null) {
          buffer.push(`Allow: ${normalizePath(path)}\n`);
        }
      }
    }

    if (rule.disallow) {
      const disallows = Array.isArray(rule.disallow) ? rule.disallow : [rule.disallow];
      for (const path of disallows) {
        if (path !== undefined && path !== null) {
          buffer.push(`Disallow: ${normalizePath(path)}\n`);
        }
      }
    }

    if (rule.crawlDelay !== undefined && rule.crawlDelay >= 0) {
      buffer.push(`Crawl-delay: ${rule.crawlDelay}\n`);
    }

    buffer.push('\n');
  }

  // Automatic root domain detection from the first sitemap when not specified
  let effectiveHost = options.host;
  const sitemaps = options.sitemap
    ? Array.isArray(options.sitemap)
      ? options.sitemap
      : [options.sitemap]
    : [];

  if (!effectiveHost && sitemaps.length > 0) {
    const autoDetectedHost = extractRootDomain(sitemaps[0]);
    if (autoDetectedHost) {
      effectiveHost = autoDetectedHost;
    }
  }

  if (effectiveHost) {
    buffer.push(`Host: ${effectiveHost.trim()}\n`);
  }

  if (sitemaps.length > 0) {
    for (const sm of sitemaps) {
      if (sm && sm.trim()) {
        buffer.push(`Sitemap: ${sm.trim()}\n`);
      }
    }
  }

  // 🛡️ v1.3.10: Final RFC sanitization pass
  return sanitizeRobotsOutput(buffer.join(''));
}