/* * Copyright (c) 2026 Fordi / FomaDev. 
 * Licensed under FomaDev Public License.
 * See LICENSE file in the project root for full license information.
 */

import { RobotsOptions } from '../../types/robots.js';

/**
 * Extraire l'origine (protocol + host) depuis une URL absolue.
 */
function extractRootDomain(url: string): string | null {
  try {
    const parsed = new URL(url);
    return parsed.origin;
  } catch {
    return null;
  }
}

/**
 * Normalise un chemin pour respecter le standard Robots.txt (doit commencer par '/').
 */
function normalizePath(path: string): string {
  const trimmed = path.trim();
  if (!trimmed) return '';
  return trimmed.startsWith('/') ? trimmed : `/${trimmed}`;
}

/**
 * Nettoie le contenu généré pour garantir la conformité RFC :
 * - Suppression des espaces de fin de ligne
 * - Normalisation des saut de lignes (LF)
 * - Compression des lignes vides consécutives (max 1 ligne vide)
 */
function sanitizeRobotsOutput(content: string): string {
  return content
    .replace(/\r\n/g, '\n')              // Normalisation LF
    .split('\n')
    .map((line) => line.trimEnd())        // Suppression des trailing spaces
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')          // Max 1 ligne vide consécutive
    .trim();
}

/**
 * Génère le contenu texte brut pour le fichier robots.txt.
 * v1.3.0 : Intégration native du helper Robots.txt.
 * v1.3.1 : Détection et chaînage automatique du domaine racine (Root Domain Auto-Discovery).
 * v1.3.2 : Typage strict KnownUserAgent avec autocomplétion IDE.
 * v1.3.4 : Mapping automatique de tableaux pour les directives d'exclusion (Disallow Array Mapping).
 * v1.3.5 : Support multi-sitemaps (Multi-Sitemap Array Injection).
 * v1.3.6 : Prise en charge complète de la directive Allow.
 * v1.3.7 : Support de la directive non-standard Crawl-delay.
 * v1.3.8 : Injection de métadonnées d'en-tête (# Generated by next-advanced-sitemap).
 * v1.3.9 : Support du générateur pour le guard de réponse HTTP text/plain.
 * v1.3.10 : Validation finale de conformité RFC (RFC Compliance Sanitizer & Guard).
 */
export function buildRobotsText(options: RobotsOptions): string {
  const buffer: string[] = [];

  // 🚀 v1.3.8 : Commentaire de métadonnées
  const generatedAt = new Date().toISOString();
  buffer.push(`# Generated by next-advanced-sitemap at ${generatedAt}\n\n`);

  const rules = Array.isArray(options.rules) ? options.rules : [options.rules];

  for (const rule of rules) {
    const userAgents = Array.isArray(rule.userAgent) ? rule.userAgent : [rule.userAgent];
    for (const agent of userAgents) {
      if (agent.trim()) {
        buffer.push(`User-agent: ${agent.trim()}\n`);
      }
    }

    if (rule.allow) {
      const allows = Array.isArray(rule.allow) ? rule.allow : [rule.allow];
      for (const path of allows) {
        if (path !== undefined && path !== null) {
          buffer.push(`Allow: ${normalizePath(path)}\n`);
        }
      }
    }

    if (rule.disallow) {
      const disallows = Array.isArray(rule.disallow) ? rule.disallow : [rule.disallow];
      for (const path of disallows) {
        if (path !== undefined && path !== null) {
          buffer.push(`Disallow: ${normalizePath(path)}\n`);
        }
      }
    }

    if (rule.crawlDelay !== undefined && rule.crawlDelay >= 0) {
      buffer.push(`Crawl-delay: ${rule.crawlDelay}\n`);
    }

    buffer.push('\n');
  }

  // Auto-détection du domaine racine depuis le premier sitemap si non spécifié
  let effectiveHost = options.host;
  const sitemaps = options.sitemap
    ? Array.isArray(options.sitemap)
      ? options.sitemap
      : [options.sitemap]
    : [];

  if (!effectiveHost && sitemaps.length > 0) {
    const autoDetectedHost = extractRootDomain(sitemaps[0]);
    if (autoDetectedHost) {
      effectiveHost = autoDetectedHost;
    }
  }

  if (effectiveHost) {
    buffer.push(`Host: ${effectiveHost.trim()}\n`);
  }

  if (sitemaps.length > 0) {
    for (const sm of sitemaps) {
      if (sm && sm.trim()) {
        buffer.push(`Sitemap: ${sm.trim()}\n`);
      }
    }
  }

  // 🛡️ v1.3.10 : Passe de sanitisation finale RFC
  return sanitizeRobotsOutput(buffer.join(''));
}